### ISSUE TITLE
does not work with jQuery 3.1

### ISSUE THREAD

**Issue by pk-fr** [jtnix/jQuery-Flyout#1]
I started to upgrade my project using JQueyFlyOut from JQuery 2.0 to JQuery 3.1..

It was working great with JQuery 2.0 and does not work anymore with JQuery 3.1...

I started to debug it and noticed that variable names starting with the "$" sign did no more receive accurate content ($holder $thumb $loader)...

then I have a problem with the following lines:

```
if (o.loadingSrc) {
            $('#'+o.loader).append($('<img/>')
                            .load(function() {
                                    $(this)
                                        .css({'position':'relative',
                                             'top':th/2-(this.height/2),
                                             'left':tw/2-(this.width/2)})
                                        .attr('alt',o.loadingText);
                                    })
                                .attr('src',o.loadingSrc)
                            );
```

it seems that the $(this) Inside load(function()  has not the expected value, but I did not go further..

Thanks for having a look and a fix to it....

Cheers,
Pascal

**Comment by jtnix** [comment]
This appears to have been fixed with either the latest 1.3 of jQuery flyout or in a more recent release of jQuery itself.
